[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "java -jar target/backend-0.0.1-SNAPSHOT.jar"
